CREATE TABLE IF NOT EXISTS public.lead_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empresa INTEGER NOT NULL,
  nome VARCHAR(120) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_lead_tags_empresa_nome
ON public.lead_tags (id_empresa, lower(nome));

CREATE INDEX IF NOT EXISTS idx_lead_tags_empresa
ON public.lead_tags (id_empresa);

CREATE TABLE IF NOT EXISTS public.lead_tag_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id INTEGER NOT NULL,
  tag_id BIGINT NOT NULL REFERENCES public.lead_tags(id) ON DELETE CASCADE,
  id_empresa INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_lead_tag_assignments_unique
ON public.lead_tag_assignments (lead_id, tag_id);

CREATE INDEX IF NOT EXISTS idx_lead_tag_assignments_empresa
ON public.lead_tag_assignments (id_empresa, lead_id);
